slam_toolbox:
  ros__parameters:
    use_sim_time: false
    map_frame: map
    odom_frame: odom
    base_frame: body
    scan_topic: /scan
    mode: mapping
    resolution: 0.05
    map_update_interval: 1.0

    transform_timeout: 1.0
    tf_buffer_duration: 60.0
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05
    throttle_scans: 10
    minimum_time_interval: 0.0
    min_laser_range: 0.05
    restamp_tf: true 
    scan_queue_size: 200